theme: jekyll-theme-cayman
title: Transifex Engineering Manifesto (TEM)
description: How Engineering works in Transifex
twitter:
  card: "summary"
  username: "transifex"
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/images/default-card.png?v=1
        height: 720
        width: 720
google_analytics: "UA-21799942-2"
